language: node_js
node_js:
  - "8"
env:
  - TEST_SUITE=contractMintedCappedCrowdsale
  - TEST_SUITE=contractDutchAuction
  - TEST_SUITE=e2eMintedCappedCrowdsale
  - TEST_SUITE=e2etDutchAuction
install:
  - npm install

before_script:
  - git submodule update --init --recursive --remote
  - npm run installWeb3
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - npm run lint
  - if [ $TEST_SUITE == 'contractMintedCappedCrowdsale' ]; then npm run testContractsMintedCappedCrowdsale; fi
  - if [ $TEST_SUITE == 'contractDutchAuction' ]; then npm run testContractsDutchAuction ; fi
  - if [ $TEST_SUITE == 'e2eMintedCappedCrowdsale' ]; then npm run e2eMintedCappedCrowdsale ; fi
  - if [ $TEST_SUITE == 'e2etDutchAuction' ]; then npm run e2eDutchAuction; fi
  - npm run coveralls

after_script:
  - sudo kill `sudo lsof -t -i:8545`

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
